"""add product indexes for is_finished_product country_of_origin and name

Revision ID: 527b7d06729d
Revises: e4f5a6b7c8d9
Create Date: 2026-03-02 22:55:20.700747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527b7d06729d'
down_revision: Union[str, None] = 'e4f5a6b7c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_products_country', 'products', ['country_of_origin'], unique=False)
    op.create_index('idx_products_is_finished', 'products', ['is_finished_product'], unique=False)
    op.create_index('idx_products_name', 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_products_name', table_name='products')
    op.drop_index('idx_products_is_finished', table_name='products')
    op.drop_index('idx_products_country', table_name='products')
    # ### end Alembic commands ###
