"""Initial schema with 5 tables and BOM view

Revision ID: aff16d8a8bf7
Revises:
Create Date: 2025-10-23 16:59:30.784469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff16d8a8bf7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=False),
    sa.Column('co2e_factor', sa.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('geography', sa.String(length=50), nullable=True),
    sa.Column('reference_year', sa.Integer(), nullable=True),
    sa.Column('data_quality_rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('uncertainty_min', sa.DECIMAL(precision=15, scale=8), nullable=True),
    sa.Column('uncertainty_max', sa.DECIMAL(precision=15, scale=8), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('co2e_factor >= 0', name='ck_emission_factor_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_name', 'data_source', 'geography', 'reference_year', name='uq_emission_factor_composite')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_finished_product', sa.Boolean(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("unit IN ('unit', 'kg', 'g', 'L', 'mL', 'm', 'cm', 'kWh', 'MJ')", name='ck_product_unit'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('bill_of_materials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('parent_product_id', sa.String(length=32), nullable=False),
    sa.Column('child_product_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=15, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('parent_product_id != child_product_id', name='ck_bom_no_self_reference'),
    sa.CheckConstraint('quantity > 0', name='ck_bom_quantity_positive'),
    sa.ForeignKeyConstraint(['child_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_product_id', 'child_product_id', name='uq_bom_parent_child')
    )
    op.create_table('pcf_calculations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('calculation_type', sa.String(length=50), nullable=True),
    sa.Column('total_co2e_kg', sa.DECIMAL(precision=15, scale=6), nullable=False),
    sa.Column('materials_co2e', sa.DECIMAL(precision=15, scale=6), nullable=True),
    sa.Column('energy_co2e', sa.DECIMAL(precision=15, scale=6), nullable=True),
    sa.Column('transport_co2e', sa.DECIMAL(precision=15, scale=6), nullable=True),
    sa.Column('waste_co2e', sa.DECIMAL(precision=15, scale=6), nullable=True),
    sa.Column('primary_data_share', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('data_quality_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('calculation_method', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('calculated_by', sa.String(length=100), nullable=True),
    sa.Column('calculation_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("calculation_type IN ('cradle_to_gate', 'cradle_to_grave', 'gate_to_gate')", name='ck_calculation_type'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculation_details',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('calculation_id', sa.String(length=32), nullable=False),
    sa.Column('component_id', sa.String(length=32), nullable=True),
    sa.Column('component_name', sa.String(length=255), nullable=False),
    sa.Column('component_level', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=15, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('emission_factor_id', sa.String(length=32), nullable=True),
    sa.Column('emissions_kg_co2e', sa.DECIMAL(precision=15, scale=6), nullable=True),
    sa.Column('data_quality', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_id'], ['pcf_calculations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Create indexes for products table
    op.create_index('idx_products_code', 'products', ['code'])
    op.create_index('idx_products_category', 'products', ['category'])
    op.create_index('idx_products_finished', 'products', ['is_finished_product'])

    # Create indexes for emission_factors table
    op.create_index('idx_ef_activity', 'emission_factors', ['activity_name'])
    op.create_index('idx_ef_geography', 'emission_factors', ['geography'])
    op.create_index('idx_ef_source', 'emission_factors', ['data_source'])

    # Create indexes for bill_of_materials table
    op.create_index('idx_bom_parent', 'bill_of_materials', ['parent_product_id'])
    op.create_index('idx_bom_child', 'bill_of_materials', ['child_product_id'])

    # Create indexes for pcf_calculations table
    op.create_index('idx_calc_product', 'pcf_calculations', ['product_id'])
    op.create_index('idx_calc_date', 'pcf_calculations', ['created_at'])
    op.create_index('idx_calc_status', 'pcf_calculations', ['status'])

    # Create indexes for calculation_details table
    op.create_index('idx_detail_calc', 'calculation_details', ['calculation_id'])
    op.create_index('idx_detail_component', 'calculation_details', ['component_id'])

    # Create v_bom_explosion view for recursive BOM traversal
    op.execute("""
        CREATE VIEW v_bom_explosion AS
        WITH RECURSIVE bom_tree AS (
            -- Base case: Start with finished products
            SELECT
                p.id AS root_id,
                p.name AS root_name,
                p.id AS component_id,
                p.name AS component_name,
                0 AS level,
                1.0 AS cumulative_quantity,
                p.unit,
                p.id AS path
            FROM products p
            WHERE p.is_finished_product = 1

            UNION ALL

            -- Recursive case: Traverse BOM
            SELECT
                bt.root_id,
                bt.root_name,
                child.id AS component_id,
                child.name AS component_name,
                bt.level + 1,
                bt.cumulative_quantity * bom.quantity,
                COALESCE(bom.unit, child.unit) AS unit,
                bt.path || '/' || child.id AS path
            FROM bom_tree bt
            JOIN bill_of_materials bom ON bt.component_id = bom.parent_product_id
            JOIN products child ON bom.child_product_id = child.id
            WHERE bt.level < 10  -- Prevent infinite recursion
              AND INSTR(bt.path, child.id) = 0  -- Prevent cycles
        )
        SELECT * FROM bom_tree
    """)


def downgrade() -> None:
    # Drop view first
    op.execute("DROP VIEW IF EXISTS v_bom_explosion")

    # Drop indexes for calculation_details
    op.drop_index('idx_detail_component', table_name='calculation_details')
    op.drop_index('idx_detail_calc', table_name='calculation_details')

    # Drop indexes for pcf_calculations
    op.drop_index('idx_calc_status', table_name='pcf_calculations')
    op.drop_index('idx_calc_date', table_name='pcf_calculations')
    op.drop_index('idx_calc_product', table_name='pcf_calculations')

    # Drop indexes for bill_of_materials
    op.drop_index('idx_bom_child', table_name='bill_of_materials')
    op.drop_index('idx_bom_parent', table_name='bill_of_materials')

    # Drop indexes for emission_factors
    op.drop_index('idx_ef_source', table_name='emission_factors')
    op.drop_index('idx_ef_geography', table_name='emission_factors')
    op.drop_index('idx_ef_activity', table_name='emission_factors')

    # Drop indexes for products
    op.drop_index('idx_products_finished', table_name='products')
    op.drop_index('idx_products_category', table_name='products')
    op.drop_index('idx_products_code', table_name='products')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation_details')
    op.drop_table('pcf_calculations')
    op.drop_table('bill_of_materials')
    op.drop_table('products')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
